name: seguro
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.7.0







dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3       # Gerenciamento de estado (BLoC)
  firebase_core: ^2.14.0     # Firebase (core)
  firebase_auth: ^4.9.0      # Autenticação
  cloud_firestore: ^4.8.0    # Banco de dados (Firestore)
  firebase_storage: ^11.5.0  # Upload de arquivos (apólices)
  #google_ml_kit: ^0.13.0     # OCR para scan de apólices
  google_mlkit_barcode_scanning: ^0.14.1
  #flutter_local_notifications: ^15.1.1 # Notificações locais
  flutter_local_notifications: ^19.3.1
  intl: ^0.18.1
  fpdart: ^1.1.1
  
  
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^5.0.0





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/
    - assets/icon/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
